import fs from "node:fs"
import path from "node:path"
import { describe, expect, it } from "vitest"

const SMOKE_SOURCE = fs.readFileSync(path.join(process.cwd(), "scripts/e2e/run-playwright-smoke.js"), "utf8")

describe("playwright smoke matrix guard", () => {
    it("keeps representative routes and browser journeys in the smoke script", () => {
        expect(SMOKE_SOURCE).toContain('"/en/base64-encode-decode"')
        expect(SMOKE_SOURCE).toContain('"/en/pipeline-builder"')
        expect(SMOKE_SOURCE).toContain('"/en/csv-json-converter"')
        expect(SMOKE_SOURCE).toContain("assertBase64PipelineSafeNavigationJourney")
        expect(SMOKE_SOURCE).toContain("assertQrDownloadJourney")
        expect(SMOKE_SOURCE).toContain('page.waitForEvent("download")')
        expect(SMOKE_SOURCE).toContain('"qr-code.png"')
        expect(SMOKE_SOURCE).toContain('"qr-code.svg"')
        expect(SMOKE_SOURCE).toContain('getByRole("tab", { name: "Decode image"')
        expect(SMOKE_SOURCE).toContain("qr-decoded-output")
        expect(SMOKE_SOURCE).toContain('name: "blank.png"')
        expect(SMOKE_SOURCE).toContain("assertPipelineRecipeJourney")
        expect(SMOKE_SOURCE).toContain("assertMonacoFallbackJourney")
        expect(SMOKE_SOURCE).toContain("assertMobileCommandPaletteJourney")
        expect(SMOKE_SOURCE).toContain("assertMobileToolPageJourneys")
        expect(SMOKE_SOURCE).toContain("assertMobileReviewMatrix")
        expect(SMOKE_SOURCE).toContain("assertAxeSeriousCriticalMatrix")
        expect(SMOKE_SOURCE).toContain("assertInputIntentSizingMatrix")
        expect(SMOKE_SOURCE).toContain("assertBasicAccessibility")
    })

    it("keeps real mobile and desktop input-intent sizing measurements", () => {
        expect(SMOKE_SOURCE).toContain("INPUT_INTENT_AUDIT_ROUTES")
        expect(SMOKE_SOURCE).toContain("INPUT_INTENT_AUDIT_VIEWPORTS")
        expect(SMOKE_SOURCE).toContain('if (arg === "--input-intents-only")')
        expect(SMOKE_SOURCE).toContain("runInputIntentSmoke")
        expect(SMOKE_SOURCE).toContain('{ width: 390, height: 844, mobile: true }')
        expect(SMOKE_SOURCE).toContain('{ width: 1280, height: 900, mobile: false }')
        expect(SMOKE_SOURCE).toContain('route: "/en/qr-code-generator"')
        expect(SMOKE_SOURCE).toContain('route: "/en/csv-json-converter"')
        expect(SMOKE_SOURCE).toContain('document.querySelectorAll("[data-input-intent]")')
        expect(SMOKE_SOURCE).toContain("getBoundingClientRect")
        expect(SMOKE_SOURCE).toContain('page.screenshot({ animations: "disabled", fullPage: false })')
        expect(SMOKE_SOURCE).toContain("assertNoHorizontalOverflow(page, routeLabel)")
    })

    it("keeps mobile tool-page regression coverage for core workflows", () => {
        expect(SMOKE_SOURCE).toContain("MOBILE_TOOL_VIEWPORTS")
        expect(SMOKE_SOURCE).toContain('{ width: 390, height: 844 }')
        expect(SMOKE_SOURCE).toContain('{ width: 430, height: 932 }')
        expect(SMOKE_SOURCE).toContain('route: "/en/json-formatter"')
        expect(SMOKE_SOURCE).toContain('route: "/en/base64-encode-decode"')
        expect(SMOKE_SOURCE).toContain('route: "/en/jwt-decoder"')
        expect(SMOKE_SOURCE).toContain('route: "/en/regex-tester"')
        expect(SMOKE_SOURCE).toContain('route: "/en/crontab-generator"')
        expect(SMOKE_SOURCE).toContain('route: "/en/image-resizer"')
        expect(SMOKE_SOURCE).toContain('route: "/en/json-diff-viewer"')
        expect(SMOKE_SOURCE).toContain('route: "/en/text-diff-checker"')
        expect(SMOKE_SOURCE).toContain("assertMobileImageResizer")
        expect(SMOKE_SOURCE).toContain("assertMobileJsonDiffViewer")
        expect(SMOKE_SOURCE).toContain("assertMobileTextDiffChecker")
        expect(SMOKE_SOURCE).toContain('getByRole("dialog", { name: /Show filters/i })')
        expect(SMOKE_SOURCE).toContain("assertNoHorizontalOverflow")
        expect(SMOKE_SOURCE).toContain("clickCopyAndExpectToast")
        expect(SMOKE_SOURCE).toContain("MOBILE_REVIEW_ROUTES")
        expect(SMOKE_SOURCE).toContain('"/en/install-app"')
        expect(SMOKE_SOURCE).toContain('"/en/trust-center"')
    })

    it("keeps PWA smoke opt-in so CI can cover service worker behavior after export", () => {
        expect(SMOKE_SOURCE).toContain('if (arg === "--pwa")')
        expect(SMOKE_SOURCE).toContain("assertPwaShellJourney")
        expect(SMOKE_SOURCE).toContain("serviceWorkers: \"allow\"")
        expect(SMOKE_SOURCE).toContain("await context.setOffline(true)")
        expect(SMOKE_SOURCE).toContain("byteflow-tool-chunks-v")
        expect(SMOKE_SOURCE).toContain("byteflow-pwa-external-probe")
        expect(SMOKE_SOURCE).toContain("External request probe was cached")
        expect(SMOKE_SOURCE).toContain("/en/install-app")
        expect(SMOKE_SOURCE).toContain("Clear cached app files")
        expect(SMOKE_SOURCE).toContain('headers: { accept: "text/html" }')
    })

    it("keeps throttled first-load CLS, theme, locale, and hydration screenshot coverage", () => {
        expect(SMOKE_SOURCE).toContain("FIRST_LOAD_CLS_BUDGET = 0.1")
        expect(SMOKE_SOURCE).toContain('id: "mobile-390x844"')
        expect(SMOKE_SOURCE).toContain('id: "desktop-1280x800"')
        expect(SMOKE_SOURCE).toContain('route: "/en/qr-code-generator"')
        expect(SMOKE_SOURCE).toContain('route: "/en/json-formatter"')
        expect(SMOKE_SOURCE).toContain('route: "/en/all-tools"')
        expect(SMOKE_SOURCE).toContain('route: "/zh-CN/qr-code-generator"')
        expect(SMOKE_SOURCE).toContain('preferredLocale: "zh-CN"')
        expect(SMOKE_SOURCE).toContain('observer.observe({ type: "layout-shift", buffered: true })')
        expect(SMOKE_SOURCE).toContain('cdp.send("Network.emulateNetworkConditions"')
        expect(SMOKE_SOURCE).toContain('cdp.send("Emulation.setCPUThrottlingRate"')
        expect(SMOKE_SOURCE).toContain("capturePreHydrationState")
        expect(SMOKE_SOURCE).toContain("captureHydratedState")
        expect(SMOKE_SOURCE).toContain("captureWarmReloadState")
        expect(SMOKE_SOURCE).toContain("warmReload: true")
        expect(SMOKE_SOURCE).toContain('page.reload({ waitUntil: "domcontentloaded"')
        expect(SMOKE_SOURCE).toContain('page.screenshot({ animations: "disabled", fullPage: false })')
        expect(SMOKE_SOURCE).toContain('"byteflow:tools:favorites"')
        expect(SMOKE_SOURCE).toContain("assertFirstLoadStabilityMatrix")
    })
})
